#!/usr/bin/env ruby

require 'begin'
require 'begin/output'

begin
  Begin::CLI.start(ARGV)
rescue Interrupt
  Begin::Output.error 'Process Interrupted'
  exit 1
rescue StandardError => e
  Begin::Output.error e.message
  exit 1
end
